fake_joint_driver_node:
  ros__parameters:
    start_position:
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      values:
        - 0.0
        - 0.0
        - 0.0
        - -1.5707963
        - 0.0
        - 1.5707963
        - 0.78539816
